### ISSUE TITLE
How to load quantized weight?

### ISSUE THREAD

**Issue by mxjyst** [efeslab/Atom#14]
Hi, I want to how to  load the quantized weight to do evaluation?

**Comment by happierpig** [comment]
Hi @mxjyst ,

Thanks for your interest in our project. Currently, the codebase is a prototype for reproducing the experiments in our paper. We do not save the quantized weight and each time we do the fake quantization from scratch. Sorry for any inconvenience. Please stay tuned for future enhancements.
