### ISSUE TITLE
The question about calib data

### ISSUE THREAD

**Issue by mxjyst** [efeslab/Atom#15]
Hi, I am wandering which dataset should be the calib dataset? I want to evaluate the quantized model on my own dataset. Which dataset to generate the calib data? my own dataset or other public dataset like wikitext?

**Comment by happierpig** [comment]
Hi @mxjyst ,

You can go with WikiText-2. The calib dataset should be different from the evaluation dataset to demonstrate the generality.

**Comment by happierpig** [comment]
By the way, we updated the codebase recently to support FP4 accuracy evaluation. You can try it with arg "--quant_type fp".

**Comment by mxjyst** [comment]
I'll try it later. Thanks a lot.
