### ISSUE TITLE
Question regarding the efficiency evaluation

### ISSUE THREAD

**Issue by FlyFoxPlayer** [efeslab/Atom#17]
Hello, regarding the efficiency evaluation experiment, it seems that there are only codes for evaluating the throughput and latency of Atom and SmoothQuant. I would like to ask how the throughput and latency results for FP16 and AWQ were obtained?

**Comment by happierpig** [comment]
Hi @FlyFoxPlayer,

Thanks for your interest and issue.

I'm sorry for leaving out the eval scripts for W4A16 and FP16. We have provided the experiments setup as well as reproduce scrips in this [commit](https://github.com/efeslab/Atom/commit/060a393518bdded9961dc7ab6c6d73e5dde57373).

**Comment by FlyFoxPlayer** [comment]
Hello @happierpig, 
is the FP16.cu file also missing in the project directory kernels/baselines/src? I want to know how to evaluate FP16 baseline.

**Comment by happierpig** [comment]
Hi @FlyFoxPlayer,

Basically, we are using PyTorch to evaluate the performance of FP16 baselines. For e2e results, [nn.Linear](https://github.com/efeslab/Atom/blob/060a393518bdded9961dc7ab6c6d73e5dde57373/e2e/punica-fp16/punica/models/llama.py#L53) is used as FP16 GEMM. For kernel results, we provided scripts as [here](https://github.com/efeslab/Atom/blob/060a393518bdded9961dc7ab6c6d73e5dde57373/kernels/baselines/python-api.ipynb#L236).
