### ISSUE TITLE
LLM model load hanging problem

### ISSUE THREAD

**Issue by jimmy-adams** [efeslab/Atom#18]
Hello,
When i follow the guidance and try reproduce the result, i encounter the problem shown in the screening below.

<img width="965" alt="1719457102248" src="https://github.com/efeslab/Atom/assets/41593649/7e7a8f17-37cd-42a9-a78c-a2a72aca705b">

**Comment by happierpig** [comment]
Hi @jimmy-adams ,

Could you please provide more information like the dependent library env and the GPU types? so that we can reproduce this issue. Thanks!

**Comment by jimmy-adams** [comment]
> Hi @jimmy-adams ,
> 
> Could you please provide more information like the dependent library env and the GPU types? so that we can reproduce this issue. Thanks!

Dear author,
Thank you for your reply. I think i missed some dependency lib in my computer, now it is working.
