### ISSUE TITLE
Is it possible to add support for other models?

### ISSUE THREAD

**Issue by wlll123456** [efeslab/Atom#21]
Hi, this is great work. I found under /Atom/model/main.py file that it seems to only support llama, opt, mixtral models. If I need to add support for Qwen model, which files should I change?

**Comment by happierpig** [comment]
Hi @wlll123456 ,

Thanks for your interest! Sure it is possible to add support for models with human efforts. Basically, you need to add wrapper functions corresponding to the model architecture. You can follow this commit(7dafad02d6837ca1436d1c2bbec9c9edfd475e0e) where we add support for Mixtral models.
