### ISSUE TITLE
ppl on ptb

### ISSUE THREAD

**Issue by MrDoghead** [efeslab/Atom#3]
When I ran your code, I found that the ppl score of the llama-7B model on the PTB dataset is greater than 20, whether quantized or not. And in another paper, the score is also different from yours. Why?

<img width="651" alt="Screenshot 2024-01-12 at 19 10 49" src="https://github.com/efeslab/Atom/assets/35255512/acec9687-6f2e-4638-9240-1ec752a3589c">

**Comment by happierpig** [comment]
Hi @MrDoghead ,

Thanks for reporting the issue. I suppose the mismatch comes from the model you are using. 

1. The results we reported in our paper are aligned with [SpQR](https://arxiv.org/abs/2306.03078).
2. We evaluate widely used [deca-llama](https://huggingface.co/baffo32/decapoda-research-llama-7B-hf). Huggy-llama may show different results.
3. PTB is relatively small, therefore results are more erratic.

**Comment by happierpig** [comment]
After 24 hours
