### ISSUE TITLE
how to compare the performance with vllm/tgit/lightllm or other llm serving framework?

### ISSUE THREAD

**Issue by irasin** [efeslab/Atom#4]
Great works!
I was wondering do you have some online or offline inference api that can be used to test the throughput/latency performance and will the performance be superior compared with vllm/tgit/lightllm, etc.?

Hope to get your answer, thanks

**Comment by happierpig** [comment]
Hi @irasin ,

Thanks for your great questions! Here are some of my thoughts and please stay tuned.

1. Atom is a quantization approach, which is a piece of inference optimization techniques and is orthonormal to a "serving framework". Atom can be evaluated on different frameworks (vLLM, lightLLM, Punica, etc.) compared with different quantization mechanisms. And we arbitrarily chose [Punica](https://github.com/punica-ai/punica).
2. This codebase is a minimal version for reproducing the experiment results in our paper. The algorithm and kernels are coupled with and manually integrated into Punica's codebase. Currently, it doesn't provide an easy-to-use API to deploy Atom. We plan to do this later.

**Comment by irasin** [comment]
Thanks a lot, I'm looking forward to use your deploying API ASAP.
