### ISSUE TITLE
the ppl for llama-7b is very large

### ISSUE THREAD

**Issue by priscilla-pan** [efeslab/Atom#7]
I have reproduced the results of llama-7b. 
The ppl of WikiText2 is the same as it in Table 3（6.16）.
The ppl of c4 is also the same as it in Table 3 (7.694).
But the ppl of ptb is very large （32.879）， it is 9.62 in Table 3.  why ?

**Comment by priscilla-pan** [comment]
i use [deca-llama](https://huggingface.co/baffo32/decapoda-research-llama-7B-hf)...

**Comment by priscilla-pan** [comment]
i do use [deca-llama](https://huggingface.co/baffo32/decapoda-research-llama-7B-hf)...

**Comment by cylinbao** [comment]
Hi @priscilla-pan, I just re-run our ppl eval for ptb and I am able to get 9.611 ppl with Atom's W4A4 quantization. I wonder what is the ppl you get on PTB even without quantization (W16A16)? Our is 8.802, also matched what we reported. 

![Screenshot 2024-02-22 at 9 48 05 PM](https://github.com/efeslab/Atom/assets/6966352/9aaa9e81-8047-46a5-937f-da2cf92e76dd)
