### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by muzi0111** [efeslab/Atom#9]
I attempted the W4A4 operation on the OPT-350M model and was able to obtain the corresponding results. However, after switching the model to 2.7B, I encountered a mismatch error at line 238 in quant.py. Upon printing, I discovered the size to be ([32, 2048, 160]), whereas, for the 350M model, it was displayed as 16, 2048, 128. How should I resolve this error?

**Comment by happierpig** [comment]
Hi @muzi0111,

Thanks for your interest in our project.

About the assertion error, I'm assuming you are referring to [L235](https://github.com/efeslab/Atom/blob/main/model/quant.py#L235) in quant.py. The quantization method applied to KV-Cache is group quant with the granularity of per head. Therefore, this assertion is to ensure the last dimension (which will be the reduction dimension in group quant) has the shape of _head_dim_. 128 here is widely used _head_dim_ in newly released models for efficiency consideration.

To resolve this error, I think replacing 128 with head_dim will be a good choice.
